- name: Configure servers
  hosts: homelab
  become: true

  roles:
  - lxd
  - localhost-remote-lxd

- name: create bee-server containers
  hosts: bee-server
  become: true
  gather_facts: false

  tasks:
  - name: register local storage
    command: lxc storage volume list local -f yaml
    register: local_storage
    changed_when: false

  - name: create appdata volume
    when: (local_storage.stdout | from_yaml | map(attribute='name')) is not contains("appdata")
    command: lxc storage volume create local appdata

  - name: mnt-appdata profile defined
    lxd_profile:
      name: mnt-appdata
      description: mount appdata volume to /mnt/appdata
      devices:
        appdata:
          path: /mnt/appdata
          pool: local
          source: appdata
          type: disk

  - name: bee-docker created
    lxd_container:
      name: bee-docker
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: debian/12/cloud
      profiles:
      - default
      - docker
      - mnt-appdata
      wait_for_container: true
      timeout: 600

- name: Configure bee-docker
  hosts: bee-docker

  roles:
  - timezone

  tasks:
  - name: python3-debian installed
    apt:
      name:
      - python3-debian
      state: latest
      update_cache: true

  - name: add docker repository
    deb822_repository:
      name: docker
      types: deb
      uris: https://download.docker.com/linux/debian
      suites: "{{ ansible_distribution_release }}"
      components: stable
      architectures: amd64
      signed_by: https://download.docker.com/linux/debian/gpg

  - name: docker installed
    apt:
      name:
#      - intel-media-va-driver-non-free
#      - intel-opencl-icd
      - docker-ce 
      state: latest
      update_cache: true
