config:
  core.https_address: '[::]:8443'
storage_pools:
- config:
    source: /var/snap/lxd/common/lxd/storage-pools/local
  description: Local btrfs storage
  name: local
  driver: btrfs
profiles:
- config:
    limits.cpu.allowance: 100%
    limits.memory: 2GiB
  description: Default LXD profile
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: local
      type: disk
  name: default
- config:
    cloud-init.user-data: |
      #cloud-config
      apt:
        sources:
          ansible:
            source: "ppa:ansible/ansible"
      packages:
      - ansible
  description: Additional controller profile
  name: controller
