---
- name: snapd installed
  apt: name=snapd

- name: sudoers secure_path includes /snap/bin
  copy:
    src: secure-path
    dest: /etc/sudoers.d/secure-path
    owner: root
    group: root
    mode: 0440

- name: Set snap refresh timer
  command: "snap set system refresh.timer=1:00-4:00"
  changed_when: false

- name: core snap installed
  snap: name=core
  ignore_errors: true
