---
- name: unattended-upgrades is installed
  apt:
    name:
    - unattended-upgrades

- name: Configure unattended-upgrades
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

