debian:
  hosts:
    bee-server:
      ansible_host: 10.0.0.4

ubuntu:
  hosts:

lxd_servers:
  hosts:
    bee-server:

homelab:
  children:
    debian:
    ubuntu:
  vars:
    ansible_user: victoitor
    ansible_ssh_private_key_file: /home/victoitor/MEGA/ssh-keys/victoitor
