debian:
  hosts:
    bee-server:
      ansible_host: 192.168.0.3
      render_id: 105

ubuntu:
  hosts:

lxd_servers:
  hosts:
    bee-server:

homelab:
  children:
    debian:
    ubuntu:
  vars:
    ansible_user: victoitor
    ansible_ssh_private_key_file: /root/.ssh/victoitor
