debian:
  hosts:
#    bee-server:
#      ansible_host: 10.0.0.4
#      render_id: 105
    router-server:
      ansible_host: 10.0.0.10
      render_id: 105

ubuntu:
  hosts:

incus_servers:
  hosts:
#    bee-server:
    router-server

homelab:
  children:
    debian:
    ubuntu:
  vars:
    ansible_user: victoitor
    ansible_ssh_private_key_file: /root/.ssh/victoitor
