debian:
  hosts:
    beelink4125:
      ansible_host: 10.0.0.4
      target_ip: 10.0.0.4
      interface: enp2s0

ubuntu:
  hosts:

lxd_servers:
  hosts:
    beelink4125:

homelab:
  children:
    debian:
    ubuntu:
  vars:
    ansible_user: victoitor
    ansible_ssh_private_key_file: /home/victoitor/MEGA/ssh-keys/victoitor
