---
- name: run update-initramfs
  command: update-initramfs -u

- name: run update-grub
  command: update-grub

- name: Output reboot message
  debug:
    msg: "Rebooting is necessry to update kernel modules"
