---

- name: Gather localhost facts
  hosts: localhost

  tasks:
  - name: Local machine identifier
    set_fact:
      local_identifier: "{{ ansible_user }}@{{ ansible_hostname }}"

  - name: Print localhost facts
    debug:
      var: ansible_facts

  - name: Print localhost facts
    debug:
      msg: "local_identifier={{ local_identifier }}"

- hosts: homelab
  become: true

  tasks:
  - name: Get lxd trust list
    command: lxc config trust list -f yaml
    register: trust_list
    changed_when: false

  - name: Print lxd yaml
    debug:
      var: trust_list.stdout | from_yaml

  - name: Get trusted client names
    set_fact:
      trust_client_names: "{{ trust_client_names|default([]) + [item.name] }}"
    when: item.type == "client"
    loop: "{{ trust_list.stdout | from_yaml }}"

  - name: Output trust_list
    debug:
      var: trust_client_names
