---

- name: Gather localhost facts
  hosts: localhost

  tasks:
    #  - name: Print all available facts
    #    ansible.builtin.debug:
    #      var: ansible_facts

  - name: Set local machine identifier
    set_fact:
      local_identifier: "{{ ansible_facts['user_id'] }}@{{ ansible_facts['nodename'] }}"

- hosts: homelab
  become: true

  tasks:
  - name: Get lxd trust list
    command: lxc config trust list -f yaml
    register: trust_list
    changed_when: false

  - name: Get trusted client names
    set_fact:
      trust_client_names: "{{ trust_list.stdout | from_yaml | selectattr('type', '==', 'client') | map(attribute='name') }}"

  - name: Add remote to local machine
    when: hostvars['localhost']['local_identifier'] not in trust_client_names
    block:
    - name: Add lxd trusted client
      command: "lxc config trust add --name {{ hostvars['localhost']['local_identifier'] }}"
      register: trust_add_output

      #  - name:
      #    debug:
      #      var: trust_add_output

    - name: Add local remote
      become: false
      delegate_to: localhost
      command: "lxc remote add {{ ansible_facts['nodename'] }} {{ trust_add_output.stdout_lines[1] }}"
