- name: add repository
  deb822_repository:
    name: incus
    types: deb
    uris: https://pkgs.zabbly.com/incus/stable
    suites: bookworm
    components: main
    architectures: amd64
    signed_by: https://pkgs.zabbly.com/key.asc
    
- name: install
  apt:
    state: present
    name: 
    - incus
    - incus-ui-canonical
    update_cache: true

- name: hold incus and incus-ui-canonical
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
  - incus
  - incus-ui-canonical

- name: "{{ ansible_user }} in incus-admin group"
  user:
    name: "{{ ansible_user }}"
    groups: incus-admin
    append: true
